import { AbilityResultContent, NaturalAbility } from '@/types/naturalAbility';

export const ABILITY_RESULTS: Record<NaturalAbility, AbilityResultContent> = {
  Diviner: {
    ability: 'Diviner',
    subtitle: 'The Pattern Reader',
    explanation:
      'You notice hidden meanings, signs, motives, timing, and the things people almost say but do not.',
    strength: 'You can read between the lines before most people know there are lines.',
    shadow: 'You may overread silence when you are craving certainty.',
    growthPrompt:
      'Where am I seeing a real pattern, and where am I creating one because I need certainty?',
    feedSymbol: '◇',
    glow: '#a78bfa',
    accent: 'from-violet-500 to-fuchsia-500',
  },
  Reaper: {
    ability: 'Reaper',
    subtitle: 'The Ending Maker',
    explanation: 'You know when something is dead, fake, expired, toxic, or no longer aligned.',
    strength: 'You protect your future by ending what cannot come with you.',
    shadow: 'You may cut things off before giving them a real chance to heal.',
    growthPrompt: 'Am I ending this because it is truly dead, or because I am afraid to repair it?',
    feedSymbol: '☾',
    glow: '#f43f5e',
    accent: 'from-rose-600 to-red-900',
  },
  Empath: {
    ability: 'Empath',
    subtitle: 'The Energy Feeler',
    explanation:
      'You feel emotional shifts deeply and often sense what people are carrying before they say it.',
    strength: 'You make people feel emotionally seen.',
    shadow: 'You may absorb feelings that do not belong to you.',
    growthPrompt: 'Is this feeling mine, or did I pick it up from someone else?',
    feedSymbol: '♡',
    glow: '#ec4899',
    accent: 'from-pink-500 to-rose-500',
  },
  Charmer: {
    ability: 'Charmer',
    subtitle: 'The Pull',
    explanation: 'You naturally attract attention, comfort, laughter, loyalty, or desire.',
    strength: 'You can shift a room with presence.',
    shadow: 'You may use charm to avoid being fully vulnerable.',
    growthPrompt: 'Am I being magnetic because I am present, or performing because I want approval?',
    feedSymbol: '✦',
    glow: '#f59e0b',
    accent: 'from-amber-400 to-yellow-500',
  },
  Alchemist: {
    ability: 'Alchemist',
    subtitle: 'The Transformer',
    explanation: 'You turn pain, chaos, failure, and pressure into wisdom, beauty, or power.',
    strength: 'You know how to make meaning from what tried to break you.',
    shadow: 'You may wait for pain before allowing yourself to grow.',
    growthPrompt: 'What am I ready to turn into power without needing more pain first?',
    feedSymbol: '⚗',
    glow: '#10b981',
    accent: 'from-emerald-500 to-teal-500',
  },
  Herbalist: {
    ability: 'Herbalist',
    subtitle: 'The Grounded Restorer',
    explanation:
      'You restore through care, body wisdom, food, rest, nature, protection, and practical love.',
    strength: 'You know how to bring people back to earth.',
    shadow: 'You may care for everyone else while neglecting your own body.',
    growthPrompt: 'Where does my body need care before my mind tries to solve everything?',
    feedSymbol: '❧',
    glow: '#22c55e',
    accent: 'from-green-500 to-emerald-600',
  },
  Seer: {
    ability: 'Seer',
    subtitle: 'The Future Noticer',
    explanation: 'You sense what is coming and notice future patterns before others catch up.',
    strength: 'You prepare for shifts before they become obvious.',
    shadow: 'You may live in what might happen instead of what is happening.',
    growthPrompt:
      'What future am I sensing, and what can I do today to prepare without panicking?',
    feedSymbol: '◉',
    glow: '#06b6d4',
    accent: 'from-cyan-500 to-blue-500',
  },
  Shapeshifter: {
    ability: 'Shapeshifter',
    subtitle: 'The Reinvention Artist',
    explanation: 'You adapt quickly, survive change, and become what the moment requires.',
    strength: 'You can move through rooms, eras, and versions of yourself.',
    shadow: 'You may lose track of your truth while adapting to survive.',
    growthPrompt: 'Which version of me is survival, and which version of me is truth?',
    feedSymbol: '⟡',
    glow: '#8b5cf6',
    accent: 'from-violet-500 to-purple-600',
  },
  Healer: {
    ability: 'Healer',
    subtitle: 'The Peace Bringer',
    explanation: 'You help people soften, recover, breathe, forgive, and feel human again.',
    strength: 'You create emotional safety.',
    shadow: 'You may try to heal people who keep choosing the wound.',
    growthPrompt: 'Who am I trying to heal that has not chosen healing for themselves?',
    feedSymbol: '✚',
    glow: '#14b8a6',
    accent: 'from-teal-400 to-cyan-500',
  },
  Dreamer: {
    ability: 'Dreamer',
    subtitle: 'The World Imaginer',
    explanation: 'You move through imagination, emotion, symbolism, fantasy, and possibility.',
    strength: 'You can imagine life beyond what is currently visible.',
    shadow: 'You may escape into dreams instead of building them.',
    growthPrompt: 'Which dream deserves a plan?',
    feedSymbol: '☁',
    glow: '#818cf8',
    accent: 'from-indigo-400 to-purple-500',
  },
  Prophet: {
    ability: 'Prophet',
    subtitle: 'The Truth Speaker',
    explanation: 'You say what others avoid and carry messages people may need but resist.',
    strength: 'You bring truth into rooms that are pretending.',
    shadow: 'You may be so direct that people cannot receive the message.',
    growthPrompt: 'How can I tell the truth in a way people can actually receive?',
    feedSymbol: '✧',
    glow: '#facc15',
    accent: 'from-yellow-400 to-amber-500',
  },
  Ungifted: {
    ability: 'Ungifted',
    subtitle: 'The Unreadable',
    explanation:
      'This does not mean powerless. It means the system cannot clearly read you. Your ability may be hidden, blocked, still forming, or outside the known categories.',
    strength: 'You resist simple labels.',
    shadow: 'You may feel disconnected from your own power.',
    growthPrompt: 'What if my gift is not missing, but still hidden from language?',
    feedSymbol: '∅',
    glow: '#94a3b8',
    accent: 'from-slate-500 to-slate-700',
  },
  Manifestor: {
    ability: 'Manifestor',
    subtitle: 'The Reality Caller',
    explanation:
      'You turn intention into reality through focus, belief, momentum, and action.',
    strength: 'You can move an idea from thought into outcome.',
    shadow: 'You may get frustrated when reality does not move as fast as your vision.',
    growthPrompt: 'What am I calling in, and what action proves I believe it?',
    feedSymbol: '✹',
    glow: '#d946ef',
    accent: 'from-fuchsia-500 to-pink-500',
  },
  Creative: {
    ability: 'Creative',
    subtitle: 'The World Builder',
    explanation:
      'You turn feelings, ideas, sounds, visuals, stories, pain, and identity into something people can experience.',
    strength: 'You translate the invisible into something real.',
    shadow: 'You may carry too many unfinished worlds at once.',
    growthPrompt: 'What am I carrying inside that deserves to become real?',
    feedSymbol: '✎',
    glow: '#f0abfc',
    accent: 'from-pink-400 to-purple-500',
  },
};

export function getSignalBlend(primary: NaturalAbility, secondary: NaturalAbility): string {
  if (primary === secondary) return ABILITY_RESULTS[primary].subtitle;
  const blends: Record<string, string> = {
    'Creative-Manifestor': 'The World Builder',
    'Manifestor-Creative': 'The Reality Architect',
    'Reaper-Prophet': 'The Sword of Truth',
    'Prophet-Reaper': 'The Truth Executioner',
    'Empath-Healer': 'The Soft Anchor',
    'Healer-Empath': 'The Quiet Sanctuary',
    'Diviner-Seer': 'The Time Reader',
    'Seer-Diviner': 'The Signal Decoder',
    'Charmer-Manifestor': 'The Magnetic Mover',
    'Alchemist-Creative': 'The Pain Translator',
    'Shapeshifter-Charmer': 'The Room Walker',
    'Herbalist-Healer': 'The Living Garden',
    'Dreamer-Creative': 'The Vision Weaver',
  };
  const key = `${primary}-${secondary}`;
  return blends[key] || `The ${primary} ${secondary}`;
}
