import type { PrescribeMeQuestion } from "./prescribeMeTypes";

export const PRESCRIBE_ME_QUESTIONS: PrescribeMeQuestion[] = [
  {
    id: "currentNeed",
    category: "currentNeed",
    text: "What do you need right now?",
    options: [
      { label: "I need to feel understood", value: "feel_understood" },
      { label: "I need to turn up", value: "turn_up" },
      { label: "I need to calm down", value: "calm_down" },
      { label: "I need to focus", value: "focus" },
      { label: "I need to discover something new", value: "discover_new" },
      { label: "I need motivation", value: "motivation" },
      { label: "I need to process something", value: "process" },
      { label: "I need creative inspiration", value: "creative_inspiration" },
      { label: "I need background energy", value: "background_energy" },
      { label: "I need community / live energy", value: "live_energy" },
    ],
  },
  {
    id: "emotionalState",
    category: "emotionalState",
    text: "What's your current energy?",
    options: [
      { label: "Heavy", value: "heavy" },
      { label: "Restless", value: "restless" },
      { label: "Inspired", value: "inspired" },
      { label: "Numb", value: "numb" },
      { label: "Excited", value: "excited" },
      { label: "Reflective", value: "reflective" },
      { label: "Confident", value: "confident" },
      { label: "Lonely", value: "lonely" },
      { label: "Focused", value: "focused" },
      { label: "Social", value: "social" },
    ],
  },
  {
    id: "desiredShift",
    category: "desiredShift",
    text: "What do you want the content to do for you?",
    options: [
      { label: "Match my mood", value: "match_mood" },
      { label: "Change my mood", value: "change_mood" },
      { label: "Challenge me", value: "challenge_me" },
      { label: "Comfort me", value: "comfort_me" },
      { label: "Hype me up", value: "hype_up" },
      { label: "Help me create", value: "help_create" },
      { label: "Help me decide what to play", value: "help_decide" },
      { label: "Help me find my people", value: "find_people" },
    ],
  },
  {
    id: "familiarity",
    category: "familiarity",
    text: "Do you want familiar energy or discovery?",
    options: [
      { label: "Keep it familiar", value: "familiar" },
      { label: "Mix familiar with new", value: "hybrid" },
      { label: "Surprise me", value: "surprise" },
      { label: "Underground only", value: "underground" },
      { label: "Trending only", value: "trending" },
    ],
  },
  {
    id: "contentType",
    category: "contentType",
    text: "What kind of route do you want?",
    options: [
      { label: "Song", value: "song" },
      { label: "Station", value: "station" },
      { label: "Artist station", value: "artist_station" },
      { label: "Live radio show", value: "live_show" },
      { label: "DJ mix", value: "dj_mix" },
      { label: "Producer beat", value: "producer_beat" },
      { label: "Song Wars battle", value: "song_wars" },
      { label: "Playlist", value: "playlist" },
      { label: "Replay", value: "replay" },
      { label: "Community room", value: "community" },
      { label: "Broadcast idea", value: "broadcast_idea" },
      { label: "Release strategy", value: "release_strategy" },
      { label: "Show flow", value: "show_flow" },
    ],
  },
];

export const REFINEMENT_OPTIONS = [
  { id: "calmer", label: "Make it calmer", description: "Lower the energy levels" },
  { id: "harder", label: "Make it harder", description: "Raise the energy levels" },
  {
    id: "familiar",
    label: "Make it more familiar",
    description: "Tune closer to your current catalog saves",
  },
  {
    id: "surprising",
    label: "Make it more surprising",
    description: "Infuse high discovery and underground cuts",
  },
  {
    id: "live_only",
    label: "Include live content",
    description: "Prioritize live streams and interactive slots",
  },
  {
    id: "no_song_wars",
    label: "Remove Song Wars",
    description: "Filter out active PvP voting grids",
  },
  {
    id: "producer_dj",
    label: "Include producer/DJ content",
    description: "Incorporate exclusive beat packs and transition guides",
  },
];
