import { IMG } from '../data';
import type { TradioIdentity, TradioRole, TradioRoleGrant } from './types';

const roleGrant = (identityId: string, role: TradioRole, role_status: TradioRoleGrant['role_status'] = 'active'): TradioRoleGrant => ({
  id: `${identityId}-${role}`,
  role,
  role_status,
  granted_at: '2026-05-29T12:00:00Z',
  role_metadata: {},
});

export const MOCK_TRADIO_IDENTITIES = {
  fan: {
    user_id: '11111111-1111-4111-8111-111111111111',
    profile_id: '21111111-1111-4111-8111-111111111111',
    public_profile_uid: 'treytv_fan_jordan_001',
    trey_tv_uid: 'TTV-JORDAN-001',
    display_name: 'Jordan',
    username: 'jordanlistens',
    avatar_url: IMG.jordan,
    active_mode: 'listener',
    default_mode: 'listener',
    roles: [roleGrant('fan', 'fan')],
    badges: [{ id: 'top-fan', label: 'Top Fan', tone: 'cyan' }],
    verification_status: 'unverified',
    broadcast_access_status: 'invite_only',
    access_state: 'available',
    city: 'Memphis',
    region: 'TN',
    fan_interests: ['artist stations', 'song wars', 'late-night radio'],
  },
  artist: {
    user_id: '22222222-2222-4222-8222-222222222222',
    profile_id: '32222222-2222-4222-8222-222222222222',
    public_profile_uid: 'treytv_artist_mila_rain',
    trey_tv_uid: 'TTV-MILA-RAIN',
    display_name: 'Mila Rain',
    username: 'milarain',
    avatar_url: IMG.milaRain,
    active_mode: 'artist',
    default_mode: 'artist',
    roles: [roleGrant('artist', 'fan'), roleGrant('artist', 'artist')],
    badges: [{ id: 'verified-artist', label: 'Verified Artist', tone: 'magenta' }],
    verification_status: 'verified',
    broadcast_access_status: 'pending',
    access_state: 'available',
    genres: ['R&B', 'Soul'],
  },
  producer: {
    user_id: '33333333-3333-4333-8333-333333333333',
    profile_id: '43333333-3333-4333-8333-333333333333',
    public_profile_uid: 'treytv_producer_darius_cole',
    trey_tv_uid: 'TTV-DARIUS-COLE',
    display_name: 'Darius Cole',
    username: 'dariusmakesbeats',
    avatar_url: IMG.dariusCole,
    active_mode: 'producer',
    default_mode: 'producer',
    roles: [roleGrant('producer', 'fan'), roleGrant('producer', 'producer')],
    badges: [{ id: 'beatmaker', label: 'Beat Maker', tone: 'violet' }],
    verification_status: 'verified',
    broadcast_access_status: 'submitted',
    access_state: 'available',
    genres: ['Trap Soul', 'Lo-Fi'],
  },
  dj: {
    user_id: '44444444-4444-4444-8444-444444444444',
    profile_id: '54444444-4444-4444-8444-444444444444',
    public_profile_uid: 'treytv_dj_midnight_spin',
    trey_tv_uid: 'TTV-DJ-MIDNIGHT',
    display_name: 'DJ Midnight Spin',
    username: 'midnightspin',
    avatar_url: IMG.lateNightSoul,
    active_mode: 'dj',
    default_mode: 'dj',
    roles: [roleGrant('dj', 'fan'), roleGrant('dj', 'dj')],
    badges: [{ id: 'host', label: 'Radio Host', tone: 'gold' }],
    verification_status: 'verified',
    broadcast_access_status: 'cleared',
    access_state: 'available',
    genres: ['Hip-Hop', 'House', 'Live Radio'],
  },
  multi: {
    user_id: '55555555-5555-4555-8555-555555555555',
    profile_id: '65555555-5555-4555-8555-555555555555',
    public_profile_uid: 'treytv_creator_trey_trizzy',
    trey_tv_uid: 'TTV-TREY-TRIZZY',
    display_name: 'Trey Trizzy',
    username: 'treytrizzy',
    avatar_url: IMG.treyTrizzy,
    active_mode: 'artist',
    default_mode: 'artist',
    roles: [roleGrant('multi', 'fan'), roleGrant('multi', 'artist'), roleGrant('multi', 'producer')],
    badges: [{ id: 'verified-artist', label: 'Verified Artist', tone: 'magenta' }, { id: 'producer', label: 'Producer', tone: 'violet' }],
    verification_status: 'verified',
    broadcast_access_status: 'cleared',
    access_state: 'available',
    genres: ['R&B', 'Rap', 'Trap Soul'],
  },
  admin: {
    user_id: '66666666-6666-4666-8666-666666666666',
    profile_id: '76666666-6666-4666-8666-666666666666',
    public_profile_uid: 'treytv_owner_platform',
    trey_tv_uid: 'TTV-OWNER-ROOT',
    display_name: 'Trizzy Trey',
    username: 'trizzytrey',
    avatar_url: IMG.aiSphere,
    active_mode: 'admin',
    default_mode: 'admin',
    roles: [roleGrant('admin', 'fan'), roleGrant('admin', 'moderator'), roleGrant('admin', 'admin'), roleGrant('admin', 'owner')],
    badges: [{ id: 'owner', label: 'Platform Owner', tone: 'emerald' }],
    verification_status: 'verified',
    broadcast_access_status: 'cleared',
    access_state: 'available',
  },
  // Profile activation state test identities for Pass 4I
  artist_pending: {
    user_id: '77777777-7777-4777-8777-777777777777',
    profile_id: '87777777-7777-4777-8777-777777777777',
    public_profile_uid: 'treytv_artist_alicia_pending',
    trey_tv_uid: 'TTV-ALICIA-PENDING',
    display_name: 'Alicia Waves',
    username: 'aliciawaves',
    avatar_url: IMG.milaRain,
    active_mode: 'artist',
    default_mode: 'artist',
    roles: [roleGrant('artist_pending', 'fan'), { id: 'artist_pending-artist', role: 'artist', role_status: 'requested' as const }],
    badges: [],
    verification_status: 'unverified',
    broadcast_access_status: 'invite_only',
    access_state: 'available',
    genres: ['Soul', 'Indie'],
  },
  artist_incomplete: {
    user_id: '88888888-8888-4888-8888-888888888888',
    profile_id: '98888888-8888-4888-8888-888888888888',
    public_profile_uid: 'treytv_artist_leo_incomplete',
    trey_tv_uid: 'TTV-LEO-INCOMPLETE',
    display_name: 'Leo Sky',
    username: 'leosky',
    avatar_url: IMG.treyTrizzy,
    active_mode: 'artist',
    default_mode: 'artist',
    roles: [roleGrant('artist_incomplete', 'fan'), roleGrant('artist_incomplete', 'artist')],
    badges: [],
    verification_status: 'unverified',
    broadcast_access_status: 'invite_only',
    access_state: 'available',
    // Note: marked as approved but incomplete profile (will need checklist)
  },
  producer_pending: {
    user_id: '99999999-9999-4999-8999-999999999999',
    profile_id: 'aa999999-9999-4999-8999-999999999999',
    public_profile_uid: 'treytv_producer_maya_pending',
    trey_tv_uid: 'TTV-MAYA-PENDING',
    display_name: 'Maya Beats',
    username: 'mayabeats',
    avatar_url: IMG.dariusCole,
    active_mode: 'producer',
    default_mode: 'producer',
    roles: [roleGrant('producer_pending', 'fan'), { id: 'producer_pending-producer', role: 'producer', role_status: 'requested' as const }],
    badges: [],
    verification_status: 'unverified',
    broadcast_access_status: 'invite_only',
    access_state: 'available',
    genres: ['Ambient', 'Experimental'],
  },
  producer_incomplete: {
    user_id: 'bb000000-0000-4000-8000-000000000000',
    profile_id: 'cc000000-0000-4000-8000-000000000000',
    public_profile_uid: 'treytv_producer_rex_incomplete',
    trey_tv_uid: 'TTV-REX-INCOMPLETE',
    display_name: 'Rex Sound Design',
    username: 'rexsounds',
    avatar_url: IMG.dariusCole,
    active_mode: 'producer',
    default_mode: 'producer',
    roles: [roleGrant('producer_incomplete', 'fan'), roleGrant('producer_incomplete', 'producer')],
    badges: [],
    verification_status: 'unverified',
    broadcast_access_status: 'invite_only',
    access_state: 'available',
    genres: ['Tech House', 'Garage'],
  },
  dj_pending: {
    user_id: 'dd111111-1111-4111-8111-111111111111',
    profile_id: 'ee111111-1111-4111-8111-111111111111',
    public_profile_uid: 'treytv_dj_kai_pending',
    trey_tv_uid: 'TTV-KAI-PENDING',
    display_name: 'Kai Nights',
    username: 'kainights',
    avatar_url: IMG.lateNightSoul,
    active_mode: 'dj',
    default_mode: 'dj',
    roles: [roleGrant('dj_pending', 'fan'), { id: 'dj_pending-dj', role: 'dj', role_status: 'requested' as const }],
    badges: [],
    verification_status: 'unverified',
    broadcast_access_status: 'submitted',
    access_state: 'available',
    genres: ['Deep House', 'Tech'],
  },
  dj_incomplete: {
    user_id: 'ff222222-2222-4222-8222-222222222222',
    profile_id: 'gg222222-2222-4222-8222-222222222222',
    public_profile_uid: 'treytv_dj_nova_incomplete',
    trey_tv_uid: 'TTV-NOVA-INCOMPLETE',
    display_name: 'Nova Studios',
    username: 'novastudios',
    avatar_url: IMG.lateNightSoul,
    active_mode: 'dj',
    default_mode: 'dj',
    roles: [roleGrant('dj_incomplete', 'fan'), roleGrant('dj_incomplete', 'dj')],
    badges: [],
    verification_status: 'unverified',
    broadcast_access_status: 'pending',
    access_state: 'available',
    genres: ['Drum & Bass', 'Electro'],
  },
} satisfies Record<string, TradioIdentity>;

export type MockIdentityKey = keyof typeof MOCK_TRADIO_IDENTITIES;

export const DEFAULT_MOCK_IDENTITY_KEY: MockIdentityKey = 'fan';
