import { IMG } from "../data";
import type { SongWarBattle, SongWarArtist, SongWarChatMessage, SongWarReplay } from "./types";

export const MOCK_SONG_WAR_ARTISTS: Record<string, SongWarArtist> = {
  treyTrizzy: {
    id: "artist-trey",
    name: "Trey Trizzy",
    avatar: IMG.treyTrizzy,
    verified: true,
    followers: 125400,
    station: "Trey Trizzy Radio",
    stationId: "station-trey-trizzy",
  },
  kianaLane: {
    id: "artist-kiana",
    name: "Kiana Lane",
    avatar: IMG.kianaLane,
    verified: true,
    followers: 89200,
    station: "Kiana Lane Radio",
    stationId: "station-kiana-lane",
  },
  milaRain: {
    id: "artist-mila",
    name: "Mila Rain",
    avatar: IMG.milaRain,
    verified: true,
    followers: 67800,
    station: "Mila Rain Radio",
    stationId: "station-mila-rain",
  },
  jaye: {
    id: "artist-jaye",
    name: "JAYE.",
    avatar: IMG.noahKade,
    verified: true,
    followers: 54300,
    station: "JAYE. Radio",
    stationId: "station-jaye",
  },
  dariusCole: {
    id: "artist-darius",
    name: "Darius Cole",
    avatar: IMG.dariusCole,
    verified: true,
    followers: 43200,
    station: "Late Night R&B",
    stationId: "station-late-night-rb",
  },
  atlSound: {
    id: "artist-atl",
    name: "ATL Sound Machine",
    avatar: IMG.midnightVelvet,
    verified: true,
    followers: 78500,
    station: "Atlanta Heat Radio",
    stationId: "station-atl-heat",
  },
  laWaves: {
    id: "artist-la",
    name: "LA Wave Makers",
    avatar: IMG.midnightDrive,
    verified: true,
    followers: 91000,
    station: "LA Sunset Radio",
    stationId: "station-la-sunset",
  },
  djSparkles: {
    id: "artist-sparkles",
    name: "DJ Sparkles",
    avatar: IMG.aiSphere,
    verified: true,
    followers: 32000,
    station: "Sparkles Mix Radio",
    stationId: "station-sparkles-mix",
  },
  djRhythm: {
    id: "artist-rhythm",
    name: "DJ Rhythm",
    avatar: IMG.lateNightSoul,
    verified: true,
    followers: 27500,
    station: "Rhythm Signal",
    stationId: "station-rhythm-signal",
  },
};

//  MOCK BATTLES
export const MOCK_BATTLES: SongWarBattle[] = [
  {
    id: "battle-1",
    title: "The Late Night Trap/Soul Clash",
    type: "Artist vs Artist",
    artistA: MOCK_SONG_WAR_ARTISTS.treyTrizzy,
    artistB: MOCK_SONG_WAR_ARTISTS.kianaLane,
    roundsCount: 3,
    rounds: [
      {
        roundNumber: 1,
        trackA: {
          id: "track-t1",
          title: "6AM Thoughts",
          artist: "Trey Trizzy",
          art: IMG.treyTrizzy,
          src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
        },
        trackB: {
          id: "track-k1",
          title: "Falling For You",
          artist: "Kiana Lane",
          art: IMG.milaRain,
          src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
        },
        votesA: 18450,
        votesB: 19120,
        winner: "B",
        duration: 90,
        status: "completed",
      },
      {
        roundNumber: 2,
        trackA: {
          id: "track-t2",
          title: "Midnight Velvet",
          artist: "Trey Trizzy",
          art: IMG.treyTrizzy,
          src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        },
        trackB: {
          id: "track-k2",
          title: "Late Night Soul",
          artist: "Kiana Lane",
          art: IMG.lateNightSoul,
          src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
        },
        votesA: 21500,
        votesB: 18900,
        winner: "A",
        duration: 90,
        status: "playing", // Active Round 2
      },
      {
        roundNumber: 3,
        trackA: {
          id: "track-t3",
          title: "Neon Heartbreak",
          artist: "Trey Trizzy",
          art: IMG.neonHeartbreak,
          src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
        },
        trackB: {
          id: "track-k3",
          title: "Smooth Vocals Live",
          artist: "Kiana Lane",
          art: IMG.flowers,
          src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
        },
        votesA: 0,
        votesB: 0,
        winner: null,
        duration: 90,
        status: "pending",
      },
    ],
    currentRoundIndex: 1, // Round 2 (0-indexed index)
    duration: 90,
    votingDuration: 45,
    hostId: "host-1",
    hostName: "DJ Midnight Spin",
    scheduleDate: "LIVE NOW",
    visibility: "Public",
    moderationMode: "Host Controlled",
    settings: {
      allowFanChat: true,
      allowGIFs: true,
      allowEmojiReactions: true,
      allowAnimatedReactions: true,
      allowFanSongRequests: false,
    },
    prize: "Tradio Premium Champion Gold Plate",
    status: "live",
    listenersCount: 14850,
    scoreA: 1,
    scoreB: 1,
    winnerId: null,
    category: "Artist vs Artist",
    official: true,
  },
  {
    id: "battle-2",
    title: "Neon Chill vs Electronic Fusion",
    type: "Producer Beat Battle",
    artistA: MOCK_SONG_WAR_ARTISTS.jaye,
    artistB: MOCK_SONG_WAR_ARTISTS.dariusCole,
    roundsCount: 3,
    rounds: [
      {
        roundNumber: 1,
        trackA: {
          id: "j-b1",
          title: "Sunset Boulevard Beat",
          artist: "JAYE.",
          art: IMG.noahKade,
          src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
        },
        trackB: {
          id: "d-b1",
          title: "Grid Runner Loop",
          artist: "Darius Cole",
          art: IMG.dariusCole,
          src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
        },
        votesA: 0,
        votesB: 0,
        winner: null,
        duration: 120,
        status: "pending",
      },
      {
        roundNumber: 2,
        trackA: {
          id: "j-b2",
          title: "Rainy Cafe Vibes",
          artist: "JAYE.",
          art: IMG.lateNightSoul,
          src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
        },
        trackB: {
          id: "d-b2",
          title: "Synthwave Skyline",
          artist: "Darius Cole",
          art: IMG.midnightDrive,
          src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
        },
        votesA: 0,
        votesB: 0,
        winner: null,
        duration: 120,
        status: "pending",
      },
      {
        roundNumber: 3,
        trackA: {
          id: "j-b3",
          title: "Midnight Coffee Loop",
          artist: "JAYE.",
          art: IMG.outOfOrbit,
          src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
        },
        trackB: {
          id: "d-b3",
          title: "Cybernetic Afterhours",
          artist: "Darius Cole",
          art: IMG.instantDrop,
          src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
        },
        votesA: 0,
        votesB: 0,
        winner: null,
        duration: 120,
        status: "pending",
      },
    ],
    currentRoundIndex: 0,
    duration: 120,
    votingDuration: 60,
    hostId: "host-2",
    hostName: "Trey Trizzy (Host State)",
    scheduleDate: "Tomorrow at 8:00 PM",
    visibility: "Public",
    moderationMode: "Auto",
    settings: {
      allowFanChat: true,
      allowGIFs: true,
      allowEmojiReactions: true,
      allowAnimatedReactions: true,
      allowFanSongRequests: true,
    },
    prize: "Ultimate Beat Producer Crown",
    status: "upcoming",
    listenersCount: 0,
    scoreA: 0,
    scoreB: 0,
    winnerId: null,
    category: "Producer Beat Battle",
    official: true,
  },
  {
    id: "battle-3",
    title: "The Indie Wave Showdown",
    type: "Fan Pick Battle",
    artistA: MOCK_SONG_WAR_ARTISTS.milaRain,
    artistB: MOCK_SONG_WAR_ARTISTS.jaye,
    roundsCount: 3,
    rounds: [
      {
        roundNumber: 1,
        trackA: {
          id: "m-s1",
          title: "Falling For You (Acoustic)",
          artist: "Mila Rain",
          art: IMG.milaRain,
          src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
        },
        trackB: {
          id: "j-s1",
          title: "City Lights",
          artist: "JAYE.",
          art: IMG.noahKade,
          src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
        },
        votesA: 0,
        votesB: 0,
        winner: null,
        duration: 90,
        status: "pending",
      },
      {
        roundNumber: 2,
        trackA: {
          id: "m-s2",
          title: "Neon Heartbreak (Cover)",
          artist: "Mila Rain",
          art: IMG.neonHeartbreak,
          src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
        },
        trackB: {
          id: "j-s2",
          title: "Under City Lights",
          artist: "JAYE.",
          art: IMG.noahKade,
          src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
        },
        votesA: 0,
        votesB: 0,
        winner: null,
        duration: 90,
        status: "pending",
      },
      {
        roundNumber: 3,
        trackA: {
          id: "m-s3",
          title: "Indie Clouds",
          artist: "Mila Rain",
          art: IMG.flowers,
          src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
        },
        trackB: {
          id: "j-s3",
          title: "Out of Orbit (Vibe Mix)",
          artist: "JAYE.",
          art: IMG.outOfOrbit,
          src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
        },
        votesA: 0,
        votesB: 0,
        winner: null,
        duration: 90,
        status: "pending",
      },
    ],
    currentRoundIndex: 0,
    duration: 90,
    votingDuration: 45,
    hostId: "host-3",
    hostName: "Kiana Lane (Host State)",
    scheduleDate: "June 5, 9:00 PM",
    visibility: "Public",
    moderationMode: "Auto",
    settings: {
      allowFanChat: true,
      allowGIFs: true,
      allowEmojiReactions: true,
      allowAnimatedReactions: true,
      allowFanSongRequests: false,
    },
    prize: "Fan Pick Champion Crest",
    status: "upcoming",
    listenersCount: 0,
    scoreA: 0,
    scoreB: 0,
    winnerId: null,
    category: "Fan Pick Battle",
    official: false,
  },
];

//  REPLAYS / COMPLETED BATTLES
export const MOCK_REPLAYS: SongWarReplay[] = [
  {
    id: "replay-1",
    battleId: "battle-completed-1",
    title: "City vs City: ATL Heat vs LA Sunsets",
    artwork: IMG.midnightVelvet,
    artistAName: "ATL Sound Machine",
    artistBName: "LA Wave Makers",
    winnerName: "ATL Sound Machine",
    scoreA: 3,
    scoreB: 2,
    totalVotes: 89450,
    peakListeners: 34100,
    playedAt: "2 days ago",
    rounds: [
      {
        roundNumber: 1,
        trackA: {
          id: "atl-r1",
          title: "Peachtree Trap",
          artist: "ATL Sound Machine",
          art: IMG.midnightVelvet,
          src: "",
        },
        trackB: {
          id: "la-r1",
          title: "Sunset Strip Cruiser",
          artist: "LA Wave Makers",
          art: IMG.midnightDrive,
          src: "",
        },
        votesA: 14200,
        votesB: 12100,
        winner: "A",
        duration: 90,
        status: "completed",
      },
      {
        roundNumber: 2,
        trackA: {
          id: "atl-r2",
          title: "Midtown Lights",
          artist: "ATL Sound Machine",
          art: IMG.lateNightSoul,
          src: "",
        },
        trackB: {
          id: "la-r2",
          title: "Venice Beach Roller",
          artist: "LA Wave Makers",
          art: IMG.flowers,
          src: "",
        },
        votesA: 11500,
        votesB: 13900,
        winner: "B",
        duration: 90,
        status: "completed",
      },
      {
        roundNumber: 3,
        trackA: {
          id: "atl-r3",
          title: "Dirty South Anthems",
          artist: "ATL Sound Machine",
          art: IMG.treyTrizzy,
          src: "",
        },
        trackB: {
          id: "la-r3",
          title: "Canyon Drive Echoes",
          artist: "LA Wave Makers",
          art: IMG.outOfOrbit,
          src: "",
        },
        votesA: 16100,
        votesB: 15300,
        winner: "A",
        duration: 90,
        status: "completed",
      },
      {
        roundNumber: 4,
        trackA: {
          id: "atl-r4",
          title: "Late Night Waffle",
          artist: "ATL Sound Machine",
          art: IMG.memphisAfterDark,
          src: "",
        },
        trackB: {
          id: "la-r4",
          title: "Hollywood Hills Afters",
          artist: "LA Wave Makers",
          art: IMG.instantDrop,
          src: "",
        },
        votesA: 9800,
        votesB: 12800,
        winner: "B",
        duration: 90,
        status: "completed",
      },
      {
        roundNumber: 5,
        trackA: {
          id: "atl-r5",
          title: "Zone 6 Final Drop",
          artist: "ATL Sound Machine",
          art: IMG.treyTrizzy,
          src: "",
        },
        trackB: {
          id: "la-r5",
          title: "Pacific Coast Highway",
          artist: "LA Wave Makers",
          art: IMG.milaRain,
          src: "",
        },
        votesA: 20100,
        votesB: 15850,
        winner: "A",
        duration: 90,
        status: "completed",
      },
    ],
  },
  {
    id: "replay-2",
    battleId: "battle-completed-2",
    title: "DJ Signal Master Mix Showdown",
    artwork: IMG.lateNightSoul,
    artistAName: "DJ Sparkles",
    artistBName: "DJ Rhythm",
    winnerName: "DJ Rhythm",
    scoreA: 1,
    scoreB: 2,
    totalVotes: 41200,
    peakListeners: 15200,
    playedAt: "1 week ago",
    rounds: [
      {
        roundNumber: 1,
        trackA: {
          id: "ds-r1",
          title: "Vocal House Mix A",
          artist: "DJ Sparkles",
          art: IMG.aiSphere,
          src: "",
        },
        trackB: {
          id: "dr-r1",
          title: "Deep R&B Transition",
          artist: "DJ Rhythm",
          art: IMG.lateNightSoul,
          src: "",
        },
        votesA: 8200,
        votesB: 7900,
        winner: "A",
        duration: 180,
        status: "completed",
      },
      {
        roundNumber: 2,
        trackA: {
          id: "ds-r2",
          title: "Electro Tech Bed",
          artist: "DJ Sparkles",
          art: IMG.instantDrop,
          src: "",
        },
        trackB: {
          id: "dr-r2",
          title: "Smooth Soul Blend",
          artist: "DJ Rhythm",
          art: IMG.midnightVelvet,
          src: "",
        },
        votesA: 6400,
        votesB: 8800,
        winner: "B",
        duration: 180,
        status: "completed",
      },
      {
        roundNumber: 3,
        trackA: {
          id: "ds-r3",
          title: "High BPM Rave",
          artist: "DJ Sparkles",
          art: IMG.outOfOrbit,
          src: "",
        },
        trackB: {
          id: "dr-r3",
          title: "Late Night Slow-Jam Cut",
          artist: "DJ Rhythm",
          art: IMG.flowers,
          src: "",
        },
        votesA: 5900,
        votesB: 11200,
        winner: "B",
        duration: 180,
        status: "completed",
      },
    ],
  },
];

//  CHAT MESSAGES FOR BATTLE 1
export const MOCK_BATTLE_CHAT_MESSAGES: SongWarChatMessage[] = [
  {
    id: "m1",
    author: "VibeGeneral",
    avatar: IMG.jordan,
    message: "ATL vs LA vibes inside the Tradio network! Let's gooo! ",
    timestamp: "3m ago",
    role: "fan",
    badge: "VIP",
  },
  {
    id: "m2",
    author: "Trey Team 4Life",
    avatar: IMG.treyTrizzy,
    message: "TREY IN THE BUILDING! SoundHelix-Song-1 hits hard!",
    timestamp: "2m ago",
    role: "artist",
    badge: "Trey Team",
    isArtist: true,
    isVerified: true,
  },
  {
    id: "m3",
    author: "Kiana_R&B_Queen",
    avatar: IMG.kianaLane,
    message: "Wait, Kiana's vocals on Falling For You is pure liquid glass ",
    timestamp: "2m ago",
    role: "fan",
    badge: "Top Fan",
  },
  {
    id: "m4",
    author: "Moderator_Dan",
    avatar: IMG.noahKade,
    message:
      "Keep the chat friendly! Slow mode is active (3s). Let's enjoy this premium VS showcase.",
    timestamp: "1m ago",
    role: "moderator",
    badge: "Mod",
  },
  {
    id: "m5",
    author: "Tradio_Expert",
    avatar: IMG.aiSphere,
    message: "The wave clashing visual is beautiful. Crowd energy is peak!",
    timestamp: "30s ago",
    role: "fan",
  },
  {
    id: "m6",
    author: "DJ Midnight Spin",
    avatar: IMG.lateNightSoul,
    message: "ROUND 2 IS UNDERWAY! Vote above when the voting panel opens!",
    timestamp: "10s ago",
    role: "dj",
    badge: "Host",
    isVerified: true,
  },
];

//  CATEGORIES
export const SONG_WAR_CATEGORIES = [
  {
    id: "cat-1",
    title: "Artist vs Artist",
    count: 12,
    desc: "Head-to-head live artist showcases going song for song.",
    bg: "from-purple-500/20 to-purple-500/5",
    icon: "Radio",
  },
  {
    id: "cat-2",
    title: "Producer Beat Battle",
    count: 8,
    desc: "Instrumental clash where producers trigger beats in real-time.",
    bg: "from-fuchsia-500/20 to-fuchsia-500/5",
    icon: "Sparkles",
  },
  {
    id: "cat-3",
    title: "DJ Mix Battle",
    count: 6,
    desc: "Transitions, edits, and live radio show blendings.",
    bg: "from-cyan-500/20 to-cyan-500/5",
    icon: "BarChart3",
  },
  {
    id: "cat-4",
    title: "City vs City",
    count: 4,
    desc: "Representative groups battling for regional airwave dominance.",
    bg: "from-pink-500/20 to-pink-500/5",
    icon: "Users",
  },
  {
    id: "cat-5",
    title: "New Release Battle",
    count: 14,
    desc: "Testing brand new drops head-to-head for playlist placement.",
    bg: "from-emerald-500/20 to-emerald-500/5",
    icon: "UploadCloud",
  },
  {
    id: "cat-6",
    title: "Fan Pick Battle",
    count: 9,
    desc: "Listener nominated matchups and song orders.",
    bg: "from-amber-500/20 to-amber-500/5",
    icon: "Heart",
  },
];
