/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrescribeMeRouteImport } from './routes/prescribe-me'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as GoLiveRouteImport } from './routes/go-live'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CreatorHubRouteImport } from './routes/creator-hub'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUidRouteImport } from './routes/u.$uid'
import { Route as CreatorHubStudioRouteImport } from './routes/creator-hub.studio'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescribeMeRoute = PrescribeMeRouteImport.update({
  id: '/prescribe-me',
  path: '/prescribe-me',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GoLiveRoute = GoLiveRouteImport.update({
  id: '/go-live',
  path: '/go-live',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorHubRoute = CreatorHubRouteImport.update({
  id: '/creator-hub',
  path: '/creator-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUidRoute = UUidRouteImport.update({
  id: '/u/$uid',
  path: '/u/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorHubStudioRoute = CreatorHubStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => CreatorHubRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/collections': typeof CollectionsRoute
  '/create': typeof CreateRoute
  '/creator-hub': typeof CreatorHubRouteWithChildren
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/go-live': typeof GoLiveRoute
  '/inbox': typeof InboxRoute
  '/latest': typeof LatestRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/prescribe-me': typeof PrescribeMeRoute
  '/settings': typeof SettingsRoute
  '/creator-hub/studio': typeof CreatorHubStudioRoute
  '/u/$uid': typeof UUidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/collections': typeof CollectionsRoute
  '/create': typeof CreateRoute
  '/creator-hub': typeof CreatorHubRouteWithChildren
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/go-live': typeof GoLiveRoute
  '/inbox': typeof InboxRoute
  '/latest': typeof LatestRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/prescribe-me': typeof PrescribeMeRoute
  '/settings': typeof SettingsRoute
  '/creator-hub/studio': typeof CreatorHubStudioRoute
  '/u/$uid': typeof UUidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/collections': typeof CollectionsRoute
  '/create': typeof CreateRoute
  '/creator-hub': typeof CreatorHubRouteWithChildren
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/go-live': typeof GoLiveRoute
  '/inbox': typeof InboxRoute
  '/latest': typeof LatestRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/prescribe-me': typeof PrescribeMeRoute
  '/settings': typeof SettingsRoute
  '/creator-hub/studio': typeof CreatorHubStudioRoute
  '/u/$uid': typeof UUidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/collections'
    | '/create'
    | '/creator-hub'
    | '/explore'
    | '/following'
    | '/go-live'
    | '/inbox'
    | '/latest'
    | '/notifications'
    | '/premium'
    | '/prescribe-me'
    | '/settings'
    | '/creator-hub/studio'
    | '/u/$uid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/collections'
    | '/create'
    | '/creator-hub'
    | '/explore'
    | '/following'
    | '/go-live'
    | '/inbox'
    | '/latest'
    | '/notifications'
    | '/premium'
    | '/prescribe-me'
    | '/settings'
    | '/creator-hub/studio'
    | '/u/$uid'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/collections'
    | '/create'
    | '/creator-hub'
    | '/explore'
    | '/following'
    | '/go-live'
    | '/inbox'
    | '/latest'
    | '/notifications'
    | '/premium'
    | '/prescribe-me'
    | '/settings'
    | '/creator-hub/studio'
    | '/u/$uid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CollectionsRoute: typeof CollectionsRoute
  CreateRoute: typeof CreateRoute
  CreatorHubRoute: typeof CreatorHubRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  FollowingRoute: typeof FollowingRoute
  GoLiveRoute: typeof GoLiveRoute
  InboxRoute: typeof InboxRoute
  LatestRoute: typeof LatestRoute
  NotificationsRoute: typeof NotificationsRoute
  PremiumRoute: typeof PremiumRoute
  PrescribeMeRoute: typeof PrescribeMeRoute
  SettingsRoute: typeof SettingsRoute
  UUidRoute: typeof UUidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescribe-me': {
      id: '/prescribe-me'
      path: '/prescribe-me'
      fullPath: '/prescribe-me'
      preLoaderRoute: typeof PrescribeMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go-live': {
      id: '/go-live'
      path: '/go-live'
      fullPath: '/go-live'
      preLoaderRoute: typeof GoLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-hub': {
      id: '/creator-hub'
      path: '/creator-hub'
      fullPath: '/creator-hub'
      preLoaderRoute: typeof CreatorHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$uid': {
      id: '/u/$uid'
      path: '/u/$uid'
      fullPath: '/u/$uid'
      preLoaderRoute: typeof UUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-hub/studio': {
      id: '/creator-hub/studio'
      path: '/studio'
      fullPath: '/creator-hub/studio'
      preLoaderRoute: typeof CreatorHubStudioRouteImport
      parentRoute: typeof CreatorHubRoute
    }
  }
}

interface CreatorHubRouteChildren {
  CreatorHubStudioRoute: typeof CreatorHubStudioRoute
}

const CreatorHubRouteChildren: CreatorHubRouteChildren = {
  CreatorHubStudioRoute: CreatorHubStudioRoute,
}

const CreatorHubRouteWithChildren = CreatorHubRoute._addFileChildren(
  CreatorHubRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CollectionsRoute: CollectionsRoute,
  CreateRoute: CreateRoute,
  CreatorHubRoute: CreatorHubRouteWithChildren,
  ExploreRoute: ExploreRoute,
  FollowingRoute: FollowingRoute,
  GoLiveRoute: GoLiveRoute,
  InboxRoute: InboxRoute,
  LatestRoute: LatestRoute,
  NotificationsRoute: NotificationsRoute,
  PremiumRoute: PremiumRoute,
  PrescribeMeRoute: PrescribeMeRoute,
  SettingsRoute: SettingsRoute,
  UUidRoute: UUidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
