/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as PrescribeMeRouteImport } from './routes/prescribe-me'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MusicReviewRouteImport } from './routes/music-review'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as GoLiveRouteImport } from './routes/go-live'
import { Route as ForYouRouteImport } from './routes/for-you'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as CreatorStudioRouteImport } from './routes/creator-studio'
import { Route as CreatorHubRouteImport } from './routes/creator-hub'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as CreatorStudioIndexRouteImport } from './routes/creator-studio.index'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as UUidRouteImport } from './routes/u.$uid'
import { Route as SettingsVerificationRouteImport } from './routes/settings.verification'
import { Route as OnboardingVoiceRouteImport } from './routes/onboarding.voice'
import { Route as MusicReviewQueueRouteImport } from './routes/music-review.queue'
import { Route as LegalDataDeletionRouteImport } from './routes/legal.data-deletion'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as CreatorStudioSubmittedRouteImport } from './routes/creator-studio.submitted'
import { Route as CreatorStudioSubmitRouteImport } from './routes/creator-studio.submit'
import { Route as CreatorStudioSubmissionsRouteImport } from './routes/creator-studio.submissions'
import { Route as CreatorStudioSettingsRouteImport } from './routes/creator-studio.settings'
import { Route as CreatorStudioScheduleRouteImport } from './routes/creator-studio.schedule'
import { Route as CreatorStudioRewardsRouteImport } from './routes/creator-studio.rewards'
import { Route as CreatorStudioInteractionsRouteImport } from './routes/creator-studio.interactions'
import { Route as CreatorStudioFansRouteImport } from './routes/creator-studio.fans'
import { Route as CreatorStudioEditRouteImport } from './routes/creator-studio.edit'
import { Route as CreatorStudioChannelRouteImport } from './routes/creator-studio.channel'
import { Route as CreatorStudioAnalyticsRouteImport } from './routes/creator-studio.analytics'
import { Route as CreatorHubStudioRouteImport } from './routes/creator-hub.studio'
import { Route as ChannelHandleRouteImport } from './routes/channel.$handle'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminViewAsRouteImport } from './routes/admin.view-as'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSiteEditorRouteImport } from './routes/admin.site-editor'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRewardsRouteImport } from './routes/admin.rewards'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRecommendationsRouteImport } from './routes/admin.recommendations'
import { Route as AdminProfileDecorationsRouteImport } from './routes/admin.profile-decorations'
import { Route as AdminMusicReviewRouteImport } from './routes/admin.music-review'
import { Route as AdminCreatorsRouteImport } from './routes/admin.creators'
import { Route as AdminContentApprovalRouteImport } from './routes/admin.content-approval'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminContentApprovalIdRouteImport } from './routes/admin.content-approval.$id'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescribeMeRoute = PrescribeMeRouteImport.update({
  id: '/prescribe-me',
  path: '/prescribe-me',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicReviewRoute = MusicReviewRouteImport.update({
  id: '/music-review',
  path: '/music-review',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GoLiveRoute = GoLiveRouteImport.update({
  id: '/go-live',
  path: '/go-live',
  getParentRoute: () => rootRouteImport,
} as any)
const ForYouRoute = ForYouRouteImport.update({
  id: '/for-you',
  path: '/for-you',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorStudioRoute = CreatorStudioRouteImport.update({
  id: '/creator-studio',
  path: '/creator-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorHubRoute = CreatorHubRouteImport.update({
  id: '/creator-hub',
  path: '/creator-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorStudioIndexRoute = CreatorStudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UUidRoute = UUidRouteImport.update({
  id: '/u/$uid',
  path: '/u/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsVerificationRoute = SettingsVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => SettingsRoute,
} as any)
const OnboardingVoiceRoute = OnboardingVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => OnboardingRoute,
} as any)
const MusicReviewQueueRoute = MusicReviewQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => MusicReviewRoute,
} as any)
const LegalDataDeletionRoute = LegalDataDeletionRouteImport.update({
  id: '/legal/data-deletion',
  path: '/legal/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorStudioSubmittedRoute = CreatorStudioSubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorStudioSubmitRoute = CreatorStudioSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorStudioSubmissionsRoute =
  CreatorStudioSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => CreatorStudioRoute,
  } as any)
const CreatorStudioSettingsRoute = CreatorStudioSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorStudioScheduleRoute = CreatorStudioScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorStudioRewardsRoute = CreatorStudioRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorStudioInteractionsRoute =
  CreatorStudioInteractionsRouteImport.update({
    id: '/interactions',
    path: '/interactions',
    getParentRoute: () => CreatorStudioRoute,
  } as any)
const CreatorStudioFansRoute = CreatorStudioFansRouteImport.update({
  id: '/fans',
  path: '/fans',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorStudioEditRoute = CreatorStudioEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorStudioChannelRoute = CreatorStudioChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorStudioAnalyticsRoute = CreatorStudioAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorHubStudioRoute = CreatorHubStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => CreatorHubRoute,
} as any)
const ChannelHandleRoute = ChannelHandleRouteImport.update({
  id: '/channel/$handle',
  path: '/channel/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminViewAsRoute = AdminViewAsRouteImport.update({
  id: '/view-as',
  path: '/view-as',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteEditorRoute = AdminSiteEditorRouteImport.update({
  id: '/site-editor',
  path: '/site-editor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecommendationsRoute = AdminRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileDecorationsRoute = AdminProfileDecorationsRouteImport.update({
  id: '/profile-decorations',
  path: '/profile-decorations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMusicReviewRoute = AdminMusicReviewRouteImport.update({
  id: '/music-review',
  path: '/music-review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreatorsRoute = AdminCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentApprovalRoute = AdminContentApprovalRouteImport.update({
  id: '/content-approval',
  path: '/content-approval',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentApprovalIdRoute = AdminContentApprovalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminContentApprovalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/collections': typeof CollectionsRoute
  '/create': typeof CreateRoute
  '/creator-hub': typeof CreatorHubRouteWithChildren
  '/creator-studio': typeof CreatorStudioRouteWithChildren
  '/edit-profile': typeof EditProfileRoute
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/for-you': typeof ForYouRoute
  '/go-live': typeof GoLiveRoute
  '/guide': typeof GuideRoute
  '/inbox': typeof InboxRoute
  '/index': typeof Char91indexChar93Route
  '/latest': typeof LatestRoute
  '/login': typeof LoginRoute
  '/music-review': typeof MusicReviewRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/premium': typeof PremiumRoute
  '/prescribe-me': typeof PrescribeMeRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/content-approval': typeof AdminContentApprovalRouteWithChildren
  '/admin/creators': typeof AdminCreatorsRoute
  '/admin/music-review': typeof AdminMusicReviewRoute
  '/admin/profile-decorations': typeof AdminProfileDecorationsRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-editor': typeof AdminSiteEditorRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin/view-as': typeof AdminViewAsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/category/$slug': typeof CategorySlugRoute
  '/channel/$handle': typeof ChannelHandleRoute
  '/creator-hub/studio': typeof CreatorHubStudioRoute
  '/creator-studio/analytics': typeof CreatorStudioAnalyticsRoute
  '/creator-studio/channel': typeof CreatorStudioChannelRoute
  '/creator-studio/edit': typeof CreatorStudioEditRoute
  '/creator-studio/fans': typeof CreatorStudioFansRoute
  '/creator-studio/interactions': typeof CreatorStudioInteractionsRoute
  '/creator-studio/rewards': typeof CreatorStudioRewardsRoute
  '/creator-studio/schedule': typeof CreatorStudioScheduleRoute
  '/creator-studio/settings': typeof CreatorStudioSettingsRoute
  '/creator-studio/submissions': typeof CreatorStudioSubmissionsRoute
  '/creator-studio/submit': typeof CreatorStudioSubmitRoute
  '/creator-studio/submitted': typeof CreatorStudioSubmittedRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/legal/data-deletion': typeof LegalDataDeletionRoute
  '/music-review/queue': typeof MusicReviewQueueRoute
  '/onboarding/voice': typeof OnboardingVoiceRoute
  '/settings/verification': typeof SettingsVerificationRoute
  '/u/$uid': typeof UUidRoute
  '/watch/$id': typeof WatchIdRoute
  '/creator-studio/': typeof CreatorStudioIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/admin/content-approval/$id': typeof AdminContentApprovalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/collections': typeof CollectionsRoute
  '/create': typeof CreateRoute
  '/creator-hub': typeof CreatorHubRouteWithChildren
  '/edit-profile': typeof EditProfileRoute
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/for-you': typeof ForYouRoute
  '/go-live': typeof GoLiveRoute
  '/guide': typeof GuideRoute
  '/inbox': typeof InboxRoute
  '/index': typeof Char91indexChar93Route
  '/latest': typeof LatestRoute
  '/login': typeof LoginRoute
  '/music-review': typeof MusicReviewRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/premium': typeof PremiumRoute
  '/prescribe-me': typeof PrescribeMeRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/content-approval': typeof AdminContentApprovalRouteWithChildren
  '/admin/creators': typeof AdminCreatorsRoute
  '/admin/music-review': typeof AdminMusicReviewRoute
  '/admin/profile-decorations': typeof AdminProfileDecorationsRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-editor': typeof AdminSiteEditorRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin/view-as': typeof AdminViewAsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/category/$slug': typeof CategorySlugRoute
  '/channel/$handle': typeof ChannelHandleRoute
  '/creator-hub/studio': typeof CreatorHubStudioRoute
  '/creator-studio/analytics': typeof CreatorStudioAnalyticsRoute
  '/creator-studio/channel': typeof CreatorStudioChannelRoute
  '/creator-studio/edit': typeof CreatorStudioEditRoute
  '/creator-studio/fans': typeof CreatorStudioFansRoute
  '/creator-studio/interactions': typeof CreatorStudioInteractionsRoute
  '/creator-studio/rewards': typeof CreatorStudioRewardsRoute
  '/creator-studio/schedule': typeof CreatorStudioScheduleRoute
  '/creator-studio/settings': typeof CreatorStudioSettingsRoute
  '/creator-studio/submissions': typeof CreatorStudioSubmissionsRoute
  '/creator-studio/submit': typeof CreatorStudioSubmitRoute
  '/creator-studio/submitted': typeof CreatorStudioSubmittedRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/legal/data-deletion': typeof LegalDataDeletionRoute
  '/music-review/queue': typeof MusicReviewQueueRoute
  '/onboarding/voice': typeof OnboardingVoiceRoute
  '/settings/verification': typeof SettingsVerificationRoute
  '/u/$uid': typeof UUidRoute
  '/watch/$id': typeof WatchIdRoute
  '/creator-studio': typeof CreatorStudioIndexRoute
  '/legal': typeof LegalIndexRoute
  '/admin/content-approval/$id': typeof AdminContentApprovalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/collections': typeof CollectionsRoute
  '/create': typeof CreateRoute
  '/creator-hub': typeof CreatorHubRouteWithChildren
  '/creator-studio': typeof CreatorStudioRouteWithChildren
  '/edit-profile': typeof EditProfileRoute
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/for-you': typeof ForYouRoute
  '/go-live': typeof GoLiveRoute
  '/guide': typeof GuideRoute
  '/inbox': typeof InboxRoute
  '/index': typeof Char91indexChar93Route
  '/latest': typeof LatestRoute
  '/login': typeof LoginRoute
  '/music-review': typeof MusicReviewRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/premium': typeof PremiumRoute
  '/prescribe-me': typeof PrescribeMeRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/content-approval': typeof AdminContentApprovalRouteWithChildren
  '/admin/creators': typeof AdminCreatorsRoute
  '/admin/music-review': typeof AdminMusicReviewRoute
  '/admin/profile-decorations': typeof AdminProfileDecorationsRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-editor': typeof AdminSiteEditorRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin/view-as': typeof AdminViewAsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/category/$slug': typeof CategorySlugRoute
  '/channel/$handle': typeof ChannelHandleRoute
  '/creator-hub/studio': typeof CreatorHubStudioRoute
  '/creator-studio/analytics': typeof CreatorStudioAnalyticsRoute
  '/creator-studio/channel': typeof CreatorStudioChannelRoute
  '/creator-studio/edit': typeof CreatorStudioEditRoute
  '/creator-studio/fans': typeof CreatorStudioFansRoute
  '/creator-studio/interactions': typeof CreatorStudioInteractionsRoute
  '/creator-studio/rewards': typeof CreatorStudioRewardsRoute
  '/creator-studio/schedule': typeof CreatorStudioScheduleRoute
  '/creator-studio/settings': typeof CreatorStudioSettingsRoute
  '/creator-studio/submissions': typeof CreatorStudioSubmissionsRoute
  '/creator-studio/submit': typeof CreatorStudioSubmitRoute
  '/creator-studio/submitted': typeof CreatorStudioSubmittedRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/legal/data-deletion': typeof LegalDataDeletionRoute
  '/music-review/queue': typeof MusicReviewQueueRoute
  '/onboarding/voice': typeof OnboardingVoiceRoute
  '/settings/verification': typeof SettingsVerificationRoute
  '/u/$uid': typeof UUidRoute
  '/watch/$id': typeof WatchIdRoute
  '/creator-studio/': typeof CreatorStudioIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/admin/content-approval/$id': typeof AdminContentApprovalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activity'
    | '/admin'
    | '/analytics'
    | '/collections'
    | '/create'
    | '/creator-hub'
    | '/creator-studio'
    | '/edit-profile'
    | '/explore'
    | '/following'
    | '/for-you'
    | '/go-live'
    | '/guide'
    | '/inbox'
    | '/index'
    | '/latest'
    | '/login'
    | '/music-review'
    | '/notifications'
    | '/onboarding'
    | '/premium'
    | '/prescribe-me'
    | '/rewards'
    | '/settings'
    | '/signup'
    | '/admin/applications'
    | '/admin/audit-log'
    | '/admin/content-approval'
    | '/admin/creators'
    | '/admin/music-review'
    | '/admin/profile-decorations'
    | '/admin/recommendations'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/site-editor'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/videos'
    | '/admin/view-as'
    | '/auth/callback'
    | '/category/$slug'
    | '/channel/$handle'
    | '/creator-hub/studio'
    | '/creator-studio/analytics'
    | '/creator-studio/channel'
    | '/creator-studio/edit'
    | '/creator-studio/fans'
    | '/creator-studio/interactions'
    | '/creator-studio/rewards'
    | '/creator-studio/schedule'
    | '/creator-studio/settings'
    | '/creator-studio/submissions'
    | '/creator-studio/submit'
    | '/creator-studio/submitted'
    | '/legal/$slug'
    | '/legal/data-deletion'
    | '/music-review/queue'
    | '/onboarding/voice'
    | '/settings/verification'
    | '/u/$uid'
    | '/watch/$id'
    | '/creator-studio/'
    | '/legal/'
    | '/admin/content-approval/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activity'
    | '/admin'
    | '/analytics'
    | '/collections'
    | '/create'
    | '/creator-hub'
    | '/edit-profile'
    | '/explore'
    | '/following'
    | '/for-you'
    | '/go-live'
    | '/guide'
    | '/inbox'
    | '/index'
    | '/latest'
    | '/login'
    | '/music-review'
    | '/notifications'
    | '/onboarding'
    | '/premium'
    | '/prescribe-me'
    | '/rewards'
    | '/settings'
    | '/signup'
    | '/admin/applications'
    | '/admin/audit-log'
    | '/admin/content-approval'
    | '/admin/creators'
    | '/admin/music-review'
    | '/admin/profile-decorations'
    | '/admin/recommendations'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/site-editor'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/videos'
    | '/admin/view-as'
    | '/auth/callback'
    | '/category/$slug'
    | '/channel/$handle'
    | '/creator-hub/studio'
    | '/creator-studio/analytics'
    | '/creator-studio/channel'
    | '/creator-studio/edit'
    | '/creator-studio/fans'
    | '/creator-studio/interactions'
    | '/creator-studio/rewards'
    | '/creator-studio/schedule'
    | '/creator-studio/settings'
    | '/creator-studio/submissions'
    | '/creator-studio/submit'
    | '/creator-studio/submitted'
    | '/legal/$slug'
    | '/legal/data-deletion'
    | '/music-review/queue'
    | '/onboarding/voice'
    | '/settings/verification'
    | '/u/$uid'
    | '/watch/$id'
    | '/creator-studio'
    | '/legal'
    | '/admin/content-approval/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activity'
    | '/admin'
    | '/analytics'
    | '/collections'
    | '/create'
    | '/creator-hub'
    | '/creator-studio'
    | '/edit-profile'
    | '/explore'
    | '/following'
    | '/for-you'
    | '/go-live'
    | '/guide'
    | '/inbox'
    | '/index'
    | '/latest'
    | '/login'
    | '/music-review'
    | '/notifications'
    | '/onboarding'
    | '/premium'
    | '/prescribe-me'
    | '/rewards'
    | '/settings'
    | '/signup'
    | '/admin/applications'
    | '/admin/audit-log'
    | '/admin/content-approval'
    | '/admin/creators'
    | '/admin/music-review'
    | '/admin/profile-decorations'
    | '/admin/recommendations'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/site-editor'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/videos'
    | '/admin/view-as'
    | '/auth/callback'
    | '/category/$slug'
    | '/channel/$handle'
    | '/creator-hub/studio'
    | '/creator-studio/analytics'
    | '/creator-studio/channel'
    | '/creator-studio/edit'
    | '/creator-studio/fans'
    | '/creator-studio/interactions'
    | '/creator-studio/rewards'
    | '/creator-studio/schedule'
    | '/creator-studio/settings'
    | '/creator-studio/submissions'
    | '/creator-studio/submit'
    | '/creator-studio/submitted'
    | '/legal/$slug'
    | '/legal/data-deletion'
    | '/music-review/queue'
    | '/onboarding/voice'
    | '/settings/verification'
    | '/u/$uid'
    | '/watch/$id'
    | '/creator-studio/'
    | '/legal/'
    | '/admin/content-approval/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivityRoute: typeof ActivityRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  CollectionsRoute: typeof CollectionsRoute
  CreateRoute: typeof CreateRoute
  CreatorHubRoute: typeof CreatorHubRouteWithChildren
  CreatorStudioRoute: typeof CreatorStudioRouteWithChildren
  EditProfileRoute: typeof EditProfileRoute
  ExploreRoute: typeof ExploreRoute
  FollowingRoute: typeof FollowingRoute
  ForYouRoute: typeof ForYouRoute
  GoLiveRoute: typeof GoLiveRoute
  GuideRoute: typeof GuideRoute
  InboxRoute: typeof InboxRoute
  Char91indexChar93Route: typeof Char91indexChar93Route
  LatestRoute: typeof LatestRoute
  LoginRoute: typeof LoginRoute
  MusicReviewRoute: typeof MusicReviewRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PremiumRoute: typeof PremiumRoute
  PrescribeMeRoute: typeof PrescribeMeRoute
  RewardsRoute: typeof RewardsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ChannelHandleRoute: typeof ChannelHandleRoute
  LegalSlugRoute: typeof LegalSlugRoute
  LegalDataDeletionRoute: typeof LegalDataDeletionRoute
  UUidRoute: typeof UUidRoute
  WatchIdRoute: typeof WatchIdRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescribe-me': {
      id: '/prescribe-me'
      path: '/prescribe-me'
      fullPath: '/prescribe-me'
      preLoaderRoute: typeof PrescribeMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music-review': {
      id: '/music-review'
      path: '/music-review'
      fullPath: '/music-review'
      preLoaderRoute: typeof MusicReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go-live': {
      id: '/go-live'
      path: '/go-live'
      fullPath: '/go-live'
      preLoaderRoute: typeof GoLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-you': {
      id: '/for-you'
      path: '/for-you'
      fullPath: '/for-you'
      preLoaderRoute: typeof ForYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-studio': {
      id: '/creator-studio'
      path: '/creator-studio'
      fullPath: '/creator-studio'
      preLoaderRoute: typeof CreatorStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-hub': {
      id: '/creator-hub'
      path: '/creator-hub'
      fullPath: '/creator-hub'
      preLoaderRoute: typeof CreatorHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-studio/': {
      id: '/creator-studio/'
      path: '/'
      fullPath: '/creator-studio/'
      preLoaderRoute: typeof CreatorStudioIndexRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$uid': {
      id: '/u/$uid'
      path: '/u/$uid'
      fullPath: '/u/$uid'
      preLoaderRoute: typeof UUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/verification': {
      id: '/settings/verification'
      path: '/verification'
      fullPath: '/settings/verification'
      preLoaderRoute: typeof SettingsVerificationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/onboarding/voice': {
      id: '/onboarding/voice'
      path: '/voice'
      fullPath: '/onboarding/voice'
      preLoaderRoute: typeof OnboardingVoiceRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/music-review/queue': {
      id: '/music-review/queue'
      path: '/queue'
      fullPath: '/music-review/queue'
      preLoaderRoute: typeof MusicReviewQueueRouteImport
      parentRoute: typeof MusicReviewRoute
    }
    '/legal/data-deletion': {
      id: '/legal/data-deletion'
      path: '/legal/data-deletion'
      fullPath: '/legal/data-deletion'
      preLoaderRoute: typeof LegalDataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-studio/submitted': {
      id: '/creator-studio/submitted'
      path: '/submitted'
      fullPath: '/creator-studio/submitted'
      preLoaderRoute: typeof CreatorStudioSubmittedRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/submit': {
      id: '/creator-studio/submit'
      path: '/submit'
      fullPath: '/creator-studio/submit'
      preLoaderRoute: typeof CreatorStudioSubmitRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/submissions': {
      id: '/creator-studio/submissions'
      path: '/submissions'
      fullPath: '/creator-studio/submissions'
      preLoaderRoute: typeof CreatorStudioSubmissionsRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/settings': {
      id: '/creator-studio/settings'
      path: '/settings'
      fullPath: '/creator-studio/settings'
      preLoaderRoute: typeof CreatorStudioSettingsRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/schedule': {
      id: '/creator-studio/schedule'
      path: '/schedule'
      fullPath: '/creator-studio/schedule'
      preLoaderRoute: typeof CreatorStudioScheduleRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/rewards': {
      id: '/creator-studio/rewards'
      path: '/rewards'
      fullPath: '/creator-studio/rewards'
      preLoaderRoute: typeof CreatorStudioRewardsRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/interactions': {
      id: '/creator-studio/interactions'
      path: '/interactions'
      fullPath: '/creator-studio/interactions'
      preLoaderRoute: typeof CreatorStudioInteractionsRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/fans': {
      id: '/creator-studio/fans'
      path: '/fans'
      fullPath: '/creator-studio/fans'
      preLoaderRoute: typeof CreatorStudioFansRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/edit': {
      id: '/creator-studio/edit'
      path: '/edit'
      fullPath: '/creator-studio/edit'
      preLoaderRoute: typeof CreatorStudioEditRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/channel': {
      id: '/creator-studio/channel'
      path: '/channel'
      fullPath: '/creator-studio/channel'
      preLoaderRoute: typeof CreatorStudioChannelRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/analytics': {
      id: '/creator-studio/analytics'
      path: '/analytics'
      fullPath: '/creator-studio/analytics'
      preLoaderRoute: typeof CreatorStudioAnalyticsRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-hub/studio': {
      id: '/creator-hub/studio'
      path: '/studio'
      fullPath: '/creator-hub/studio'
      preLoaderRoute: typeof CreatorHubStudioRouteImport
      parentRoute: typeof CreatorHubRoute
    }
    '/channel/$handle': {
      id: '/channel/$handle'
      path: '/channel/$handle'
      fullPath: '/channel/$handle'
      preLoaderRoute: typeof ChannelHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/view-as': {
      id: '/admin/view-as'
      path: '/view-as'
      fullPath: '/admin/view-as'
      preLoaderRoute: typeof AdminViewAsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-editor': {
      id: '/admin/site-editor'
      path: '/site-editor'
      fullPath: '/admin/site-editor'
      preLoaderRoute: typeof AdminSiteEditorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recommendations': {
      id: '/admin/recommendations'
      path: '/recommendations'
      fullPath: '/admin/recommendations'
      preLoaderRoute: typeof AdminRecommendationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile-decorations': {
      id: '/admin/profile-decorations'
      path: '/profile-decorations'
      fullPath: '/admin/profile-decorations'
      preLoaderRoute: typeof AdminProfileDecorationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/music-review': {
      id: '/admin/music-review'
      path: '/music-review'
      fullPath: '/admin/music-review'
      preLoaderRoute: typeof AdminMusicReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/creators': {
      id: '/admin/creators'
      path: '/creators'
      fullPath: '/admin/creators'
      preLoaderRoute: typeof AdminCreatorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-approval': {
      id: '/admin/content-approval'
      path: '/content-approval'
      fullPath: '/admin/content-approval'
      preLoaderRoute: typeof AdminContentApprovalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-approval/$id': {
      id: '/admin/content-approval/$id'
      path: '/$id'
      fullPath: '/admin/content-approval/$id'
      preLoaderRoute: typeof AdminContentApprovalIdRouteImport
      parentRoute: typeof AdminContentApprovalRoute
    }
  }
}

interface AdminContentApprovalRouteChildren {
  AdminContentApprovalIdRoute: typeof AdminContentApprovalIdRoute
}

const AdminContentApprovalRouteChildren: AdminContentApprovalRouteChildren = {
  AdminContentApprovalIdRoute: AdminContentApprovalIdRoute,
}

const AdminContentApprovalRouteWithChildren =
  AdminContentApprovalRoute._addFileChildren(AdminContentApprovalRouteChildren)

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminContentApprovalRoute: typeof AdminContentApprovalRouteWithChildren
  AdminCreatorsRoute: typeof AdminCreatorsRoute
  AdminMusicReviewRoute: typeof AdminMusicReviewRoute
  AdminProfileDecorationsRoute: typeof AdminProfileDecorationsRoute
  AdminRecommendationsRoute: typeof AdminRecommendationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSiteEditorRoute: typeof AdminSiteEditorRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminViewAsRoute: typeof AdminViewAsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminContentApprovalRoute: AdminContentApprovalRouteWithChildren,
  AdminCreatorsRoute: AdminCreatorsRoute,
  AdminMusicReviewRoute: AdminMusicReviewRoute,
  AdminProfileDecorationsRoute: AdminProfileDecorationsRoute,
  AdminRecommendationsRoute: AdminRecommendationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSiteEditorRoute: AdminSiteEditorRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminViewAsRoute: AdminViewAsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CreatorHubRouteChildren {
  CreatorHubStudioRoute: typeof CreatorHubStudioRoute
}

const CreatorHubRouteChildren: CreatorHubRouteChildren = {
  CreatorHubStudioRoute: CreatorHubStudioRoute,
}

const CreatorHubRouteWithChildren = CreatorHubRoute._addFileChildren(
  CreatorHubRouteChildren,
)

interface CreatorStudioRouteChildren {
  CreatorStudioAnalyticsRoute: typeof CreatorStudioAnalyticsRoute
  CreatorStudioChannelRoute: typeof CreatorStudioChannelRoute
  CreatorStudioEditRoute: typeof CreatorStudioEditRoute
  CreatorStudioFansRoute: typeof CreatorStudioFansRoute
  CreatorStudioInteractionsRoute: typeof CreatorStudioInteractionsRoute
  CreatorStudioRewardsRoute: typeof CreatorStudioRewardsRoute
  CreatorStudioScheduleRoute: typeof CreatorStudioScheduleRoute
  CreatorStudioSettingsRoute: typeof CreatorStudioSettingsRoute
  CreatorStudioSubmissionsRoute: typeof CreatorStudioSubmissionsRoute
  CreatorStudioSubmitRoute: typeof CreatorStudioSubmitRoute
  CreatorStudioSubmittedRoute: typeof CreatorStudioSubmittedRoute
  CreatorStudioIndexRoute: typeof CreatorStudioIndexRoute
}

const CreatorStudioRouteChildren: CreatorStudioRouteChildren = {
  CreatorStudioAnalyticsRoute: CreatorStudioAnalyticsRoute,
  CreatorStudioChannelRoute: CreatorStudioChannelRoute,
  CreatorStudioEditRoute: CreatorStudioEditRoute,
  CreatorStudioFansRoute: CreatorStudioFansRoute,
  CreatorStudioInteractionsRoute: CreatorStudioInteractionsRoute,
  CreatorStudioRewardsRoute: CreatorStudioRewardsRoute,
  CreatorStudioScheduleRoute: CreatorStudioScheduleRoute,
  CreatorStudioSettingsRoute: CreatorStudioSettingsRoute,
  CreatorStudioSubmissionsRoute: CreatorStudioSubmissionsRoute,
  CreatorStudioSubmitRoute: CreatorStudioSubmitRoute,
  CreatorStudioSubmittedRoute: CreatorStudioSubmittedRoute,
  CreatorStudioIndexRoute: CreatorStudioIndexRoute,
}

const CreatorStudioRouteWithChildren = CreatorStudioRoute._addFileChildren(
  CreatorStudioRouteChildren,
)

interface MusicReviewRouteChildren {
  MusicReviewQueueRoute: typeof MusicReviewQueueRoute
}

const MusicReviewRouteChildren: MusicReviewRouteChildren = {
  MusicReviewQueueRoute: MusicReviewQueueRoute,
}

const MusicReviewRouteWithChildren = MusicReviewRoute._addFileChildren(
  MusicReviewRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingVoiceRoute: typeof OnboardingVoiceRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingVoiceRoute: OnboardingVoiceRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface SettingsRouteChildren {
  SettingsVerificationRoute: typeof SettingsVerificationRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsVerificationRoute: SettingsVerificationRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivityRoute: ActivityRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  CollectionsRoute: CollectionsRoute,
  CreateRoute: CreateRoute,
  CreatorHubRoute: CreatorHubRouteWithChildren,
  CreatorStudioRoute: CreatorStudioRouteWithChildren,
  EditProfileRoute: EditProfileRoute,
  ExploreRoute: ExploreRoute,
  FollowingRoute: FollowingRoute,
  ForYouRoute: ForYouRoute,
  GoLiveRoute: GoLiveRoute,
  GuideRoute: GuideRoute,
  InboxRoute: InboxRoute,
  Char91indexChar93Route: Char91indexChar93Route,
  LatestRoute: LatestRoute,
  LoginRoute: LoginRoute,
  MusicReviewRoute: MusicReviewRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PremiumRoute: PremiumRoute,
  PrescribeMeRoute: PrescribeMeRoute,
  RewardsRoute: RewardsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CategorySlugRoute: CategorySlugRoute,
  ChannelHandleRoute: ChannelHandleRoute,
  LegalSlugRoute: LegalSlugRoute,
  LegalDataDeletionRoute: LegalDataDeletionRoute,
  UUidRoute: UUidRoute,
  WatchIdRoute: WatchIdRoute,
  LegalIndexRoute: LegalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
