/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as PrescribeMeRouteImport } from './routes/prescribe-me'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as GoLiveRouteImport } from './routes/go-live'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as CreatorStudioRouteImport } from './routes/creator-studio'
import { Route as CreatorHubRouteImport } from './routes/creator-hub'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreatorStudioIndexRouteImport } from './routes/creator-studio.index'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as UUidRouteImport } from './routes/u.$uid'
import { Route as OnboardingVoiceRouteImport } from './routes/onboarding.voice'
import { Route as CreatorStudioSubmittedRouteImport } from './routes/creator-studio.submitted'
import { Route as CreatorStudioSubmitRouteImport } from './routes/creator-studio.submit'
import { Route as CreatorStudioSubmissionsRouteImport } from './routes/creator-studio.submissions'
import { Route as CreatorStudioSettingsRouteImport } from './routes/creator-studio.settings'
import { Route as CreatorStudioScheduleRouteImport } from './routes/creator-studio.schedule'
import { Route as CreatorStudioRewardsRouteImport } from './routes/creator-studio.rewards'
import { Route as CreatorStudioInteractionsRouteImport } from './routes/creator-studio.interactions'
import { Route as CreatorStudioFansRouteImport } from './routes/creator-studio.fans'
import { Route as CreatorStudioEditRouteImport } from './routes/creator-studio.edit'
import { Route as CreatorStudioChannelRouteImport } from './routes/creator-studio.channel'
import { Route as CreatorStudioAnalyticsRouteImport } from './routes/creator-studio.analytics'
import { Route as CreatorHubStudioRouteImport } from './routes/creator-hub.studio'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRecommendationsRouteImport } from './routes/admin.recommendations'
import { Route as AdminCreatorsRouteImport } from './routes/admin.creators'
import { Route as AdminContentApprovalRouteImport } from './routes/admin.content-approval'
import { Route as AdminContentApprovalIdRouteImport } from './routes/admin.content-approval.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescribeMeRoute = PrescribeMeRouteImport.update({
  id: '/prescribe-me',
  path: '/prescribe-me',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GoLiveRoute = GoLiveRouteImport.update({
  id: '/go-live',
  path: '/go-live',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorStudioRoute = CreatorStudioRouteImport.update({
  id: '/creator-studio',
  path: '/creator-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorHubRoute = CreatorHubRouteImport.update({
  id: '/creator-hub',
  path: '/creator-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorStudioIndexRoute = CreatorStudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UUidRoute = UUidRouteImport.update({
  id: '/u/$uid',
  path: '/u/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingVoiceRoute = OnboardingVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => OnboardingRoute,
} as any)
const CreatorStudioSubmittedRoute = CreatorStudioSubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorStudioSubmitRoute = CreatorStudioSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorStudioSubmissionsRoute =
  CreatorStudioSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => CreatorStudioRoute,
  } as any)
const CreatorStudioSettingsRoute = CreatorStudioSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorStudioScheduleRoute = CreatorStudioScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorStudioRewardsRoute = CreatorStudioRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorStudioInteractionsRoute =
  CreatorStudioInteractionsRouteImport.update({
    id: '/interactions',
    path: '/interactions',
    getParentRoute: () => CreatorStudioRoute,
  } as any)
const CreatorStudioFansRoute = CreatorStudioFansRouteImport.update({
  id: '/fans',
  path: '/fans',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorStudioEditRoute = CreatorStudioEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorStudioChannelRoute = CreatorStudioChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorStudioAnalyticsRoute = CreatorStudioAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorHubStudioRoute = CreatorHubStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => CreatorHubRoute,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecommendationsRoute = AdminRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreatorsRoute = AdminCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentApprovalRoute = AdminContentApprovalRouteImport.update({
  id: '/content-approval',
  path: '/content-approval',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentApprovalIdRoute = AdminContentApprovalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminContentApprovalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/collections': typeof CollectionsRoute
  '/create': typeof CreateRoute
  '/creator-hub': typeof CreatorHubRouteWithChildren
  '/creator-studio': typeof CreatorStudioRouteWithChildren
  '/edit-profile': typeof EditProfileRoute
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/go-live': typeof GoLiveRoute
  '/inbox': typeof InboxRoute
  '/latest': typeof LatestRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/premium': typeof PremiumRoute
  '/prescribe-me': typeof PrescribeMeRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/content-approval': typeof AdminContentApprovalRouteWithChildren
  '/admin/creators': typeof AdminCreatorsRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/creator-hub/studio': typeof CreatorHubStudioRoute
  '/creator-studio/analytics': typeof CreatorStudioAnalyticsRoute
  '/creator-studio/channel': typeof CreatorStudioChannelRoute
  '/creator-studio/edit': typeof CreatorStudioEditRoute
  '/creator-studio/fans': typeof CreatorStudioFansRoute
  '/creator-studio/interactions': typeof CreatorStudioInteractionsRoute
  '/creator-studio/rewards': typeof CreatorStudioRewardsRoute
  '/creator-studio/schedule': typeof CreatorStudioScheduleRoute
  '/creator-studio/settings': typeof CreatorStudioSettingsRoute
  '/creator-studio/submissions': typeof CreatorStudioSubmissionsRoute
  '/creator-studio/submit': typeof CreatorStudioSubmitRoute
  '/creator-studio/submitted': typeof CreatorStudioSubmittedRoute
  '/onboarding/voice': typeof OnboardingVoiceRoute
  '/u/$uid': typeof UUidRoute
  '/watch/$id': typeof WatchIdRoute
  '/creator-studio/': typeof CreatorStudioIndexRoute
  '/admin/content-approval/$id': typeof AdminContentApprovalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/collections': typeof CollectionsRoute
  '/create': typeof CreateRoute
  '/creator-hub': typeof CreatorHubRouteWithChildren
  '/edit-profile': typeof EditProfileRoute
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/go-live': typeof GoLiveRoute
  '/inbox': typeof InboxRoute
  '/latest': typeof LatestRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/premium': typeof PremiumRoute
  '/prescribe-me': typeof PrescribeMeRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/content-approval': typeof AdminContentApprovalRouteWithChildren
  '/admin/creators': typeof AdminCreatorsRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/creator-hub/studio': typeof CreatorHubStudioRoute
  '/creator-studio/analytics': typeof CreatorStudioAnalyticsRoute
  '/creator-studio/channel': typeof CreatorStudioChannelRoute
  '/creator-studio/edit': typeof CreatorStudioEditRoute
  '/creator-studio/fans': typeof CreatorStudioFansRoute
  '/creator-studio/interactions': typeof CreatorStudioInteractionsRoute
  '/creator-studio/rewards': typeof CreatorStudioRewardsRoute
  '/creator-studio/schedule': typeof CreatorStudioScheduleRoute
  '/creator-studio/settings': typeof CreatorStudioSettingsRoute
  '/creator-studio/submissions': typeof CreatorStudioSubmissionsRoute
  '/creator-studio/submit': typeof CreatorStudioSubmitRoute
  '/creator-studio/submitted': typeof CreatorStudioSubmittedRoute
  '/onboarding/voice': typeof OnboardingVoiceRoute
  '/u/$uid': typeof UUidRoute
  '/watch/$id': typeof WatchIdRoute
  '/creator-studio': typeof CreatorStudioIndexRoute
  '/admin/content-approval/$id': typeof AdminContentApprovalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/collections': typeof CollectionsRoute
  '/create': typeof CreateRoute
  '/creator-hub': typeof CreatorHubRouteWithChildren
  '/creator-studio': typeof CreatorStudioRouteWithChildren
  '/edit-profile': typeof EditProfileRoute
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/go-live': typeof GoLiveRoute
  '/inbox': typeof InboxRoute
  '/latest': typeof LatestRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/premium': typeof PremiumRoute
  '/prescribe-me': typeof PrescribeMeRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/content-approval': typeof AdminContentApprovalRouteWithChildren
  '/admin/creators': typeof AdminCreatorsRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/creator-hub/studio': typeof CreatorHubStudioRoute
  '/creator-studio/analytics': typeof CreatorStudioAnalyticsRoute
  '/creator-studio/channel': typeof CreatorStudioChannelRoute
  '/creator-studio/edit': typeof CreatorStudioEditRoute
  '/creator-studio/fans': typeof CreatorStudioFansRoute
  '/creator-studio/interactions': typeof CreatorStudioInteractionsRoute
  '/creator-studio/rewards': typeof CreatorStudioRewardsRoute
  '/creator-studio/schedule': typeof CreatorStudioScheduleRoute
  '/creator-studio/settings': typeof CreatorStudioSettingsRoute
  '/creator-studio/submissions': typeof CreatorStudioSubmissionsRoute
  '/creator-studio/submit': typeof CreatorStudioSubmitRoute
  '/creator-studio/submitted': typeof CreatorStudioSubmittedRoute
  '/onboarding/voice': typeof OnboardingVoiceRoute
  '/u/$uid': typeof UUidRoute
  '/watch/$id': typeof WatchIdRoute
  '/creator-studio/': typeof CreatorStudioIndexRoute
  '/admin/content-approval/$id': typeof AdminContentApprovalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/admin'
    | '/analytics'
    | '/collections'
    | '/create'
    | '/creator-hub'
    | '/creator-studio'
    | '/edit-profile'
    | '/explore'
    | '/following'
    | '/go-live'
    | '/inbox'
    | '/latest'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/premium'
    | '/prescribe-me'
    | '/rewards'
    | '/settings'
    | '/signup'
    | '/admin/content-approval'
    | '/admin/creators'
    | '/admin/recommendations'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/videos'
    | '/creator-hub/studio'
    | '/creator-studio/analytics'
    | '/creator-studio/channel'
    | '/creator-studio/edit'
    | '/creator-studio/fans'
    | '/creator-studio/interactions'
    | '/creator-studio/rewards'
    | '/creator-studio/schedule'
    | '/creator-studio/settings'
    | '/creator-studio/submissions'
    | '/creator-studio/submit'
    | '/creator-studio/submitted'
    | '/onboarding/voice'
    | '/u/$uid'
    | '/watch/$id'
    | '/creator-studio/'
    | '/admin/content-approval/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/admin'
    | '/analytics'
    | '/collections'
    | '/create'
    | '/creator-hub'
    | '/edit-profile'
    | '/explore'
    | '/following'
    | '/go-live'
    | '/inbox'
    | '/latest'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/premium'
    | '/prescribe-me'
    | '/rewards'
    | '/settings'
    | '/signup'
    | '/admin/content-approval'
    | '/admin/creators'
    | '/admin/recommendations'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/videos'
    | '/creator-hub/studio'
    | '/creator-studio/analytics'
    | '/creator-studio/channel'
    | '/creator-studio/edit'
    | '/creator-studio/fans'
    | '/creator-studio/interactions'
    | '/creator-studio/rewards'
    | '/creator-studio/schedule'
    | '/creator-studio/settings'
    | '/creator-studio/submissions'
    | '/creator-studio/submit'
    | '/creator-studio/submitted'
    | '/onboarding/voice'
    | '/u/$uid'
    | '/watch/$id'
    | '/creator-studio'
    | '/admin/content-approval/$id'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/admin'
    | '/analytics'
    | '/collections'
    | '/create'
    | '/creator-hub'
    | '/creator-studio'
    | '/edit-profile'
    | '/explore'
    | '/following'
    | '/go-live'
    | '/inbox'
    | '/latest'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/premium'
    | '/prescribe-me'
    | '/rewards'
    | '/settings'
    | '/signup'
    | '/admin/content-approval'
    | '/admin/creators'
    | '/admin/recommendations'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/videos'
    | '/creator-hub/studio'
    | '/creator-studio/analytics'
    | '/creator-studio/channel'
    | '/creator-studio/edit'
    | '/creator-studio/fans'
    | '/creator-studio/interactions'
    | '/creator-studio/rewards'
    | '/creator-studio/schedule'
    | '/creator-studio/settings'
    | '/creator-studio/submissions'
    | '/creator-studio/submit'
    | '/creator-studio/submitted'
    | '/onboarding/voice'
    | '/u/$uid'
    | '/watch/$id'
    | '/creator-studio/'
    | '/admin/content-approval/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  CollectionsRoute: typeof CollectionsRoute
  CreateRoute: typeof CreateRoute
  CreatorHubRoute: typeof CreatorHubRouteWithChildren
  CreatorStudioRoute: typeof CreatorStudioRouteWithChildren
  EditProfileRoute: typeof EditProfileRoute
  ExploreRoute: typeof ExploreRoute
  FollowingRoute: typeof FollowingRoute
  GoLiveRoute: typeof GoLiveRoute
  InboxRoute: typeof InboxRoute
  LatestRoute: typeof LatestRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PremiumRoute: typeof PremiumRoute
  PrescribeMeRoute: typeof PrescribeMeRoute
  RewardsRoute: typeof RewardsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  UUidRoute: typeof UUidRoute
  WatchIdRoute: typeof WatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescribe-me': {
      id: '/prescribe-me'
      path: '/prescribe-me'
      fullPath: '/prescribe-me'
      preLoaderRoute: typeof PrescribeMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go-live': {
      id: '/go-live'
      path: '/go-live'
      fullPath: '/go-live'
      preLoaderRoute: typeof GoLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-studio': {
      id: '/creator-studio'
      path: '/creator-studio'
      fullPath: '/creator-studio'
      preLoaderRoute: typeof CreatorStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-hub': {
      id: '/creator-hub'
      path: '/creator-hub'
      fullPath: '/creator-hub'
      preLoaderRoute: typeof CreatorHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-studio/': {
      id: '/creator-studio/'
      path: '/'
      fullPath: '/creator-studio/'
      preLoaderRoute: typeof CreatorStudioIndexRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$uid': {
      id: '/u/$uid'
      path: '/u/$uid'
      fullPath: '/u/$uid'
      preLoaderRoute: typeof UUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/voice': {
      id: '/onboarding/voice'
      path: '/voice'
      fullPath: '/onboarding/voice'
      preLoaderRoute: typeof OnboardingVoiceRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/creator-studio/submitted': {
      id: '/creator-studio/submitted'
      path: '/submitted'
      fullPath: '/creator-studio/submitted'
      preLoaderRoute: typeof CreatorStudioSubmittedRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/submit': {
      id: '/creator-studio/submit'
      path: '/submit'
      fullPath: '/creator-studio/submit'
      preLoaderRoute: typeof CreatorStudioSubmitRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/submissions': {
      id: '/creator-studio/submissions'
      path: '/submissions'
      fullPath: '/creator-studio/submissions'
      preLoaderRoute: typeof CreatorStudioSubmissionsRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/settings': {
      id: '/creator-studio/settings'
      path: '/settings'
      fullPath: '/creator-studio/settings'
      preLoaderRoute: typeof CreatorStudioSettingsRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/schedule': {
      id: '/creator-studio/schedule'
      path: '/schedule'
      fullPath: '/creator-studio/schedule'
      preLoaderRoute: typeof CreatorStudioScheduleRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/rewards': {
      id: '/creator-studio/rewards'
      path: '/rewards'
      fullPath: '/creator-studio/rewards'
      preLoaderRoute: typeof CreatorStudioRewardsRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/interactions': {
      id: '/creator-studio/interactions'
      path: '/interactions'
      fullPath: '/creator-studio/interactions'
      preLoaderRoute: typeof CreatorStudioInteractionsRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/fans': {
      id: '/creator-studio/fans'
      path: '/fans'
      fullPath: '/creator-studio/fans'
      preLoaderRoute: typeof CreatorStudioFansRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/edit': {
      id: '/creator-studio/edit'
      path: '/edit'
      fullPath: '/creator-studio/edit'
      preLoaderRoute: typeof CreatorStudioEditRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/channel': {
      id: '/creator-studio/channel'
      path: '/channel'
      fullPath: '/creator-studio/channel'
      preLoaderRoute: typeof CreatorStudioChannelRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-studio/analytics': {
      id: '/creator-studio/analytics'
      path: '/analytics'
      fullPath: '/creator-studio/analytics'
      preLoaderRoute: typeof CreatorStudioAnalyticsRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator-hub/studio': {
      id: '/creator-hub/studio'
      path: '/studio'
      fullPath: '/creator-hub/studio'
      preLoaderRoute: typeof CreatorHubStudioRouteImport
      parentRoute: typeof CreatorHubRoute
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recommendations': {
      id: '/admin/recommendations'
      path: '/recommendations'
      fullPath: '/admin/recommendations'
      preLoaderRoute: typeof AdminRecommendationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/creators': {
      id: '/admin/creators'
      path: '/creators'
      fullPath: '/admin/creators'
      preLoaderRoute: typeof AdminCreatorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-approval': {
      id: '/admin/content-approval'
      path: '/content-approval'
      fullPath: '/admin/content-approval'
      preLoaderRoute: typeof AdminContentApprovalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-approval/$id': {
      id: '/admin/content-approval/$id'
      path: '/$id'
      fullPath: '/admin/content-approval/$id'
      preLoaderRoute: typeof AdminContentApprovalIdRouteImport
      parentRoute: typeof AdminContentApprovalRoute
    }
  }
}

interface AdminContentApprovalRouteChildren {
  AdminContentApprovalIdRoute: typeof AdminContentApprovalIdRoute
}

const AdminContentApprovalRouteChildren: AdminContentApprovalRouteChildren = {
  AdminContentApprovalIdRoute: AdminContentApprovalIdRoute,
}

const AdminContentApprovalRouteWithChildren =
  AdminContentApprovalRoute._addFileChildren(AdminContentApprovalRouteChildren)

interface AdminRouteChildren {
  AdminContentApprovalRoute: typeof AdminContentApprovalRouteWithChildren
  AdminCreatorsRoute: typeof AdminCreatorsRoute
  AdminRecommendationsRoute: typeof AdminRecommendationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVideosRoute: typeof AdminVideosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentApprovalRoute: AdminContentApprovalRouteWithChildren,
  AdminCreatorsRoute: AdminCreatorsRoute,
  AdminRecommendationsRoute: AdminRecommendationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVideosRoute: AdminVideosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CreatorHubRouteChildren {
  CreatorHubStudioRoute: typeof CreatorHubStudioRoute
}

const CreatorHubRouteChildren: CreatorHubRouteChildren = {
  CreatorHubStudioRoute: CreatorHubStudioRoute,
}

const CreatorHubRouteWithChildren = CreatorHubRoute._addFileChildren(
  CreatorHubRouteChildren,
)

interface CreatorStudioRouteChildren {
  CreatorStudioAnalyticsRoute: typeof CreatorStudioAnalyticsRoute
  CreatorStudioChannelRoute: typeof CreatorStudioChannelRoute
  CreatorStudioEditRoute: typeof CreatorStudioEditRoute
  CreatorStudioFansRoute: typeof CreatorStudioFansRoute
  CreatorStudioInteractionsRoute: typeof CreatorStudioInteractionsRoute
  CreatorStudioRewardsRoute: typeof CreatorStudioRewardsRoute
  CreatorStudioScheduleRoute: typeof CreatorStudioScheduleRoute
  CreatorStudioSettingsRoute: typeof CreatorStudioSettingsRoute
  CreatorStudioSubmissionsRoute: typeof CreatorStudioSubmissionsRoute
  CreatorStudioSubmitRoute: typeof CreatorStudioSubmitRoute
  CreatorStudioSubmittedRoute: typeof CreatorStudioSubmittedRoute
  CreatorStudioIndexRoute: typeof CreatorStudioIndexRoute
}

const CreatorStudioRouteChildren: CreatorStudioRouteChildren = {
  CreatorStudioAnalyticsRoute: CreatorStudioAnalyticsRoute,
  CreatorStudioChannelRoute: CreatorStudioChannelRoute,
  CreatorStudioEditRoute: CreatorStudioEditRoute,
  CreatorStudioFansRoute: CreatorStudioFansRoute,
  CreatorStudioInteractionsRoute: CreatorStudioInteractionsRoute,
  CreatorStudioRewardsRoute: CreatorStudioRewardsRoute,
  CreatorStudioScheduleRoute: CreatorStudioScheduleRoute,
  CreatorStudioSettingsRoute: CreatorStudioSettingsRoute,
  CreatorStudioSubmissionsRoute: CreatorStudioSubmissionsRoute,
  CreatorStudioSubmitRoute: CreatorStudioSubmitRoute,
  CreatorStudioSubmittedRoute: CreatorStudioSubmittedRoute,
  CreatorStudioIndexRoute: CreatorStudioIndexRoute,
}

const CreatorStudioRouteWithChildren = CreatorStudioRoute._addFileChildren(
  CreatorStudioRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingVoiceRoute: typeof OnboardingVoiceRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingVoiceRoute: OnboardingVoiceRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  CollectionsRoute: CollectionsRoute,
  CreateRoute: CreateRoute,
  CreatorHubRoute: CreatorHubRouteWithChildren,
  CreatorStudioRoute: CreatorStudioRouteWithChildren,
  EditProfileRoute: EditProfileRoute,
  ExploreRoute: ExploreRoute,
  FollowingRoute: FollowingRoute,
  GoLiveRoute: GoLiveRoute,
  InboxRoute: InboxRoute,
  LatestRoute: LatestRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PremiumRoute: PremiumRoute,
  PrescribeMeRoute: PrescribeMeRoute,
  RewardsRoute: RewardsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  UUidRoute: UUidRoute,
  WatchIdRoute: WatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
